env:
  global:
    - MODULE_NAME=com.williamrijksen.onesignal
    - TITANIUM_BRANCH=7_5_X
    - MODULE_ROOT=$PWD

cache:
  directories:
    - node_modules
    - $HOME/android-sdk
    - $HOME/Library/Caches/Homebrew
    - $HOME/Library/Application\ Support/Titanium
  timeout: 600

matrix:
  include:
    - name: iOS
      language: objective-c
      osx_image: xcode10.1
      env:
        - PLATFORM_NAME=ios
        - RELEASE_ZIP_FILE=${MODULE_ROOT}/${PLATFORM_NAME}/${MODULE_NAME}-iphone-${TRAVIS_TAG}.zip
      before_install:
        - nvm install --lts
        - nvm use --lts
        - npm install -g titanium
        - brew update > /dev/null
        - brew tap oclint/formulae
        - brew install oclint
        - oclint -version
      before_script:
        - cd ios
        - sed -i ".bak" "s/^TITANIUM_SDK_VERSION.*/TITANIUM_SDK_VERSION=`ti sdk list -o json | node -e 'console.log(JSON.parse(require("fs").readFileSync("/dev/stdin")).activeSDK)'`/" titanium.xcconfig
        - sh -c 'xcodebuild -UseModernBuildSystem=NO -dry-run | tee xcodebuild.log && oclint-xcodebuild && oclint-json-compilation-database'
        - cd ..

    - name: Android
      language: android
      jdk: oraclejdk8
      android:
        components:
          - android-28
          - build-tools-28.0.3
      env:
        - PLATFORM_NAME=android
        - RELEASE_ZIP_FILE=${MODULE_ROOT}/${PLATFORM_NAME}/dist/${MODULE_NAME}-${PLATFORM_NAME}-${TRAVIS_TAG}.zip
      before_install:
        - nvm install --lts
        - nvm use --lts
        - npm install -g titanium
        - echo y | sdkmanager "ndk-bundle"

install: ti sdk install -b ${TITANIUM_BRANCH} -d --no-progress-bars
script: sh -c 'cd ${PLATFORM_NAME} && ti build -p ${PLATFORM_NAME} -l trace -b'
before_deploy:
  - echo "deploying ${RELEASE_ZIP_FILE} to GitHub releases"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CR7C6WsEVoFF85tIZNm+4cfNKituRab0TtDMPP+n418O/WwE7ZVV19n9uELemdyQflw3sPPyzTdr/0hg7CnDL+dVMCscZPnqkTJszq8WnNYUOGPn1Mismx7SzzCF2KXIQBui0mObQrBh+ii/aTgoVYVjC80dNbsNkzOKShloZgr/51OfKY9rqkkeUW8uMY/A/5Tq2k4X7idz+F/Ndr78wP3d2Z3SGHoq51g7fvnKAsaWJ4CqSVWl23ne8Aqft0o8SfV3Uo3pjPMzs28jGk3jW7PNyHezNNxbvDJdex0E6QSndI6MR0JNJrBp4LskuzdhprsDiwSHnL7jhywwVULhobpRSVltJAwvnkv515rfKuogCuh9WZLhR34d63FZ/JX4q/1t+YBsaUbaTRgoM4/i0+S9YEeCWTo+B8DCZjordHEF3fg4Eevq/eMMijEO6/NCY5aHQJtNkUOJCS1JdYmxmBRkLTHIF+zwN0JvNVMrWOrpImz3V37EL9Fy5EAmJGRATtpn7r63p8jCQuxE5jW6zR8usFAzxJCposRt007KyrRvdQ5odKxgaMm2RORkiAcam1Y1PCmWR5wnTkJGB1D3uVtBZ8+e2eX4UkHAAg3dRMogg9v6tjCyTVkQvkabXxP98Ckdo9Jg1trBC+QVRy76ibb20Sr+ISploRwpwPPjyuY=
  file: "${RELEASE_ZIP_FILE}"
  on:
    repo: williamrijksen/com.williamrijksen.onesignal
    tags: true
